version: 0.2

env:
  parameter-store:
    SONAR_TOKEN: /cicd/sonar/sonar-token

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
    commands:
      - echo Installing dependencies
      - apt-get update -y
      - apt-get install -y wget unzip curl

      - echo Installing SonarScanner
      - export SONAR_SCANNER_VERSION=5.0.1.3006
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:$PWD/sonar-scanner-5.0.1.3006-linux/bin

      - echo Installing Trivy
      - wget https://github.com/aquasecurity/trivy/releases/download/v0.49.1/trivy_0.49.1_Linux-64bit.tar.gz
      - tar -xzf trivy_0.49.1_Linux-64bit.tar.gz
      - mv trivy /usr/local/bin/
      - chmod +x /usr/local/bin/trivy

  pre_build:
    commands:
      - echo Login to ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 317968578233.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Checking files
      - ls -la
      - cd Swiggy_clone

      - echo Running Sonar
      - sonar-scanner -Dsonar.projectKey=swiggy -Dsonar.sources=. -Dsonar.host.url=http://34.228.64.110:9000 -Dsonar.login=$SONAR_TOKEN || true

      - echo Build Docker
      - docker build -t swiggy-app .

      - echo Run Trivy
      - trivy image swiggy-app || true

      - echo Tag image
      - docker tag swiggy-app:latest 317968578233.dkr.ecr.us-east-1.amazonaws.com/swiggy-app:latest

      - echo Push image
      - docker push 317968578233.dkr.ecr.us-east-1.amazonaws.com/swiggy-app:latest

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - appspec.yaml
