version: 0.2

env:
  parameter-store:
    SONAR_TOKEN: /cicd/sonar/sonar-token

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
    commands:
      - echo "Installing dependencies..."

      - apt-get update -y
      - apt-get install -y wget unzip curl

      # ✅ Sonar Scanner
      - export SONAR_SCANNER_VERSION=5.0.1.3006
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - export PATH=$PATH:$PWD/sonar-scanner-$SONAR_SCANNER_VERSION-linux/bin

      # ✅ Trivy install (FIXED + INDENTED)
      - echo "Installing Trivy..."
      - TRIVY_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep tag_name | cut -d '"' -f 4)
      - echo "Latest Trivy version: $TRIVY_VERSION"
      - wget https://github.com/aquasecurity/trivy/releases/download/${TRIVY_VERSION}/trivy_${TRIVY_VERSION#v}_Linux-64bit.tar.gz
      - tar -xzf trivy_*_Linux-64bit.tar.gz
      - mv trivy /usr/local/bin/
      - chmod +x /usr/local/bin/trivy
      - trivy --version

  pre_build:
    commands:
      - echo "Login to ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 317968578233.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Checking files"
      - ls -la

      - echo "Move to app folder"
      - cd Swiggy_clone

      # ✅ Sonar (non-blocking)
      - echo "Running SonarQube..."
      - sonar-scanner \
        -Dsonar.projectKey=swiggy \
        -Dsonar.sources=. \
        -Dsonar.host.url=http://34.228.64.110:9000 \
        -Dsonar.login=$SONAR_TOKEN || true

      # ✅ Build image
      - echo "Building Docker image"
      - docker build -t swiggy-app .

      # ✅ Trivy scan
      - echo "Running Trivy scan"
      - trivy image --severity HIGH,CRITICAL swiggy-app || true

      # ✅ Tag
      - docker tag swiggy-app:latest 317968578233.dkr.ecr.us-east-1.amazonaws.com/swiggy-app:latest

      # ✅ Push
      - docker push 317968578233.dkr.ecr.us-east-1.amazonaws.com/swiggy-app:latest

  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - appspec.yaml
